### ISSUE TITLE
protogen(yaml): only read schema documents for templating data document

### ISSUE THREAD

**Issue by wenchy** [tableauio/tableau#118]
Design goal: support Jinja2 (or other templating libs) templating of data document
```yaml
---
"@sheet": "@TABLEAU"
ServiceConf:
  Template: true
---
# define schema
"@sheet": "@ServiceConf"
ID: uint32
Name: string
---
"@sheet": ServiceConf
ID: {{ env.id }}
Name: {{ env.name}}
{% if env.name == 'prod' %}
Enabled: true
{% else %}
Enabled: false
{% endif %}
```
