### ISSUE TITLE
YAML: support yaml

### ISSUE THREAD

**Issue by wenchy** [tableauio/tableau#53]
## Syntax v1
references:
- https://www.yamllint.com/
- https://www.programiz.com/java-programming/annotation-types
- https://docs.python.org/3/glossary.html#term-decorator
- `@type`: https://protobuf.dev/programming-guides/proto3/#json

```yaml
---
"@metasheet": "@TABLEAU"
LiteConf:
LoaderConf:
  OrderedMap: true
---
"@metasheet": LiteConf
RoleLite:
  "@type": Lite
  Expire: duration
  Count: int32
GuildLite:
  "@type": Lite
Ids: "[]int32"
Heros:
  "@type": "[]Hero"
  "@struct":
    ID: uint32
    Name: string
---
"@metasheet": LoaderConf
Servers:
  "@type": "map<string, Server>"
  "@struct":
    Name: string
    Confs:
      "@type": "map<string, Conf>"
      "@struct":
        Async: bool
        Limit: int32
---
"@sheet": LiteConf
RoleLite:
  Expire: 2h
  Count: 50
GuildLite:
  Expire: 2h
  Count: 50
Ids: [1, 2, 3]
Heros:
  - ID: 1
    Name: fish
  - ID: 2
    Name: dog
---
"@sheet": LoaderConf
Servers:
  gamesvr:
    Name: gamesvr
    Confs:
      ItemConf:
        Async: true
      DropConf:
        Async: true
  mailsvr:
    Name: mailsvr
    Confs:
      ItemConf:
        Async: true
      DropConf:
        Async: true
```

## Generated proto
```protobuf
message LiteConf {
  option (tableau.worksheet) = {name:"LiteConf"};

  Lite role_lite= 1 [(tableau.field) = {name:"RoleLite"}];
  message Lite {
    google.protobuf.Duration expire = 1 [(tableau.field) = {name:"Expire"}];
    int32 count = 2 [(tableau.field) = {name:"Count"}];
  }
  LiteInfo guild_lite= 2 [(tableau.field) = {name:"GuildLite"}];
  repeated int32 ids = 3 [(tableau.field) = {name:"Ids"}];
  repeated Hero heros = 4 [(tableau.field) = {name:"Ids"}];
  message Hero {
    uint32 id = 1 [(tableau.field) = {name:"ID"}];
    string name = 2 [(tableau.field) = {name:"Name"}];
  }
}

message LoaderConf {
  option (tableau.worksheet) = {name:"LoaderConf"};

  map<string, Server> servers = 1 [(tableau.field) = {key:"Key"}];
  message Server {
    string key = 1 [(tableau.field) = {name:"Key"}];
    string name = 2 [(tableau.field) = {name:"Name"}];
    map<string, Conf> confs= 3 [(tableau.field) = {name:"Confs" key:"Key"}];
      message Conf {
        string key = 1 [(tableau.field) = {name:"Key"}];
        bool async= 2 [(tableau.field) = {name:"Async"}];
      }
  }
}
```
